Estabiliza o card dos filmes, inclui loader de imagem
concretesolutions/flutter-moviesapp pull request #10
Opened 2021-03-17 19:22 UTC by cs-jose-freitas

Cards dos filmes funcionando, apesar dos possíveis problemas de performance.
Também injetei um loader para controlarmos requests de imagens.

2021-03-17 20:06 UTC, cs-matheus-vasconcelos requested changes
Sugestão, mudar o nome de `ImageLoader` para `ImageDownloader` pois ele não faz um loading de fato, ele só faz o download da imagem.

2021-03-17 20:06 UTC, cs-matheus-vasconcelos commented on lib/moviesList/view/MovieCard.dart
> +        child: Container(
Poderia corrigir a indentação por favor?

2021-03-18 11:59 UTC, cs-gabriela-lima approved these changes

2021-03-18 13:51 UTC, cs-matheus-vasconcelos approved these changes

2021-03-18 13:54 UTC, merged