Tab Bar
concretesolutions/flutter-moviesapp pull request #2
Opened 2021-03-08 19:44 UTC by cs-gabriela-lima

2021-03-08 20:41 UTC, cs-matheus-vasconcelos requested changes
O que acha de criar um teste para esse componente?

2021-03-08 20:41 UTC, cs-matheus-vasconcelos commented on lib/view/Favorites.dart
> +class Favorites extends StatelessWidget {
Acredito que seria interessante mudar o nome para deixar claro o tipo de widget, o que você acha de `FavoritesPage`

2021-03-08 20:41 UTC, cs-matheus-vasconcelos commented on lib/view/Movies.dart
> +class Movies extends StatelessWidget {
Acredito que seria interessante mudar o nome para deixar claro o tipo de widget, o que você acha de `MoviesPage`

2021-03-08 20:41 UTC, cs-matheus-vasconcelos commented on lib/view/TabBar.dart
> +          }
Aqui acho que daria para utilizar a lista de tabs que você criou. Algo assim:

`return tabs[i];`

2021-03-08 20:41 UTC, cs-matheus-vasconcelos commented on lib/view/TabBar.dart
> +            BottomNavigationBarItem(icon: Icon(CupertinoIcons.list_bullet), label: "Movies" ),
Se não for incomodar poderia tirar o espaço depois de "Movies" por favor?

2021-03-08 21:34 UTC, cs-jose-freitas requested changes
Muito bom!
Se puder, arruma o teste que está quebrando, se for fácil hehe ⭐️

2021-03-08 21:34 UTC, cs-jose-freitas commented on lib/view/TabBar.dart
> +              break;
Os cases do switch precisam do break? 🤔
Vi uns exemplos que não precisavam

2021-03-08 21:34 UTC, cs-jose-freitas commented on lib/view/TabBar.dart
> +          }
Boa! Só garantir que que não vai acessar um indice que não existe

2021-03-08 21:34 UTC, cs-jose-freitas commented on lib/view/TabBar.dart
> +  List<Widget> tabs = [
Dúvida para discutirmos depois: Teoricamente, esse state já é privado, mas não faria sentido `tabs` também ser?

2021-03-09 20:10 UTC, cs-matheus-vasconcelos approved these changes

2021-03-09 20:21 UTC, cs-jose-freitas approved these changes

2021-03-09 20:22 UTC, merged