Implementa camada de persistência local.
concretesolutions/flutter-moviesapp pull request #9
Opened 2021-03-17 18:01 UTC by cs-mariaelena-silveira

Foi criada a classe FavoriteStorage que possui os métodos:
- favoriteMovie
- unfavoriteMovie
- getFavoritesMovies
- isFavoriteMovie
que correspondem respectivamente as ações, favoritar, desfavoritar, pegar lista de favoritos e verificar se o filme está favoritado ou não.

2021-03-17 18:24 UTC, cs-matheus-vasconcelos commented on ios/Podfile
> +  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
só um comentário mesmo, sabe o que é pior que o cocoapods mudando seu projeto sem você ter controle? o flutter mudar seu cocoapods sem você ter controle

2021-03-17 18:28 UTC, cs-matheus-vasconcelos commented on pubspec.lock
> +  flutter: ">=1.20.0"
Seria legal alinharmos essa subida de versão, @cs-jose-freitas  e @cs-gabriela-lima

2021-03-17 18:30 UTC, cs-jose-freitas approved these changes

2021-03-17 18:30 UTC, cs-jose-freitas commented on ios/Podfile
> +  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
Ia perguntar isso, não foi algum resquício que ficou do lance de ver sobre plugins?

2021-03-17 18:31 UTC, cs-matheus-vasconcelos requested changes

2021-03-17 18:31 UTC, cs-matheus-vasconcelos commented on test/storage/FavoriteStorage_test.dart
> +      final movie2 = MovieStub.stub(12, "Ber");
Essa propriedade já esta criada e configurada no setUp, seria interessante deixar unificado.

2021-03-17 18:31 UTC, cs-matheus-vasconcelos commented on test/storage/FavoriteStorage_test.dart
> +      final movie2 = MovieStub.stub(12, "Ber");
Essa propriedade já esta criada e configurada no setUp, seria interessante deixar unificado.

2021-03-17 19:20 UTC, cs-jose-freitas commented on pubspec.lock
> +  flutter: ">=1.20.0"
Acredito que o lock faz automaticamente quando colocamos uma dependência nova

2021-03-18 19:44 UTC, cs-mariaelena-silveira commented on ios/Podfile
> +  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
anotado aqui pra ver melhor nas resposta da docuemtação

2021-03-18 19:51 UTC, cs-mariaelena-silveira commented on test/storage/FavoriteStorage_test.dart
> +      final movie2 = MovieStub.stub(12, "Ber");
feito

2021-03-18 20:05 UTC, cs-matheus-vasconcelos approved these changes

2021-03-18 20:14 UTC, merged